name: Release Please

on:
  push:
    branches: [ "main" ]

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - name: Release Please
        uses: google-github-actions/release-please-action@v4
        with:
          release-type: simple
          # You can switch to "node", "go", "python", etc. if you want language-aware changelogs
          package-name: YOUR_REPO_NAME
          changelog-types: >
            [{"type":"feat","section":"Features","hidden":false},
             {"type":"fix","section":"Bug Fixes","hidden":false},
             {"type":"docs","section":"Docs","hidden":false},
             {"type":"refactor","section":"Refactor","hidden":false},
             {"type":"perf","section":"Performance","hidden":false},
             {"type":"test","section":"Tests","hidden":true},
             {"type":"chore","section":"Chores","hidden":true}]
